from Uart_Protocol import TTest,RTest,Timer,TimerStart,ParseData,ReceivedData#串口发送接收的类
mode = "object_detect"
can_grab = 0        #是否可以抓取
receive_qrcode = 0  #是否接收到二维码
last_err_x_pos=0
last_err_y_pos=0
Find_blobs_enable=1
valid_data=0        #色块是否在中心区域
valid_data1=1       #模型识别
QRmaterial_order=0  #二维码识别的物料顺序
first_priority_order=0 #优先级1
second_priority_order=0 #优先级2
priority_order_flag=0
switch_priority_flag=0 #切换优先级
Rdata=RTest()
uart4_flag=0
uart5_flag=0
response=0           #单片机应答
uart5_data=0
test_number0 =0
test_number1 =0
test_number2 =0
test_number3 =0
test_number4 =0
test_number5 =0
grad_count=0
screen_count=0
material_timer={'red':0,'green':0,'blue':0}#字典关键字指向三个计时器时间
